#!/usr/bin/env python3
"""Regenerate index.md from the wiki's standards/ and sections/ frontmatter.
Avoids hand-maintaining links. Run after ingesting/altering parts."""
import os, re, glob, json

WIKI = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

def fm(path):
    t=open(path).read()
    m=re.match(r"^---\n(.*?)\n---", t, re.S)
    d={}
    if m:
        for line in m.group(1).splitlines():
            mm=re.match(r'([a-z_]+):\s*(.*)', line)
            if mm:
                v=mm.group(2).strip().strip('"')
                d[mm.group(1)]=v
    return d

# standards present
std={}
for p in glob.glob(os.path.join(WIKI,"standards","*.md")):
    d=fm(p); std[d.get("id","")]=d
# sections grouped by part-standard id
secs={}
for p in glob.glob(os.path.join(WIKI,"sections","*.md")):
    d=fm(p); sid=os.path.splitext(os.path.basename(p))[0]
    # derive owning standard id from filename prefix 60617-N-...
    m=re.match(r"(60617-[0-9A-Za-z.]+)-", sid)
    if m: secs.setdefault(m.group(1),[]).append((sid,d))
for k in secs:
    secs[k].sort(key=lambda x: (1,x[0]) if re.search(r'-A\d-',x[0]) else (0,x[0]))

nsym=len(glob.glob(os.path.join(WIKI,"symbols","*.md")))

# the IEC 60617 / 617 family (canonical list)
FAM=[("60617-1","617-1 (1985)","General information, general index, cross-correspondence"),
     ("60617-2","617-2 (1983)","Symbol elements, qualifying symbols & general-application symbols"),
     ("60617-3","617-3 (1983)","Conductors and connecting devices"),
     (None,"617-4","Passive components"),
     (None,"617-5","Semiconductors and electron tubes"),
     ("60617-6","617-6 (1983)","Production and conversion of electrical energy"),
     ("60617-7","617-7 (1983)","Switchgear, controlgear and protective devices"),
     ("60617-8","617-8 (1983)","Measuring instruments, lamps and signalling devices"),
     ("60617-9","617-9 (1983)","Telecommunications: switching and peripheral equipment"),
     ("60617-10","617-10 (1983)","Telecommunications: transmission"),
     (None,"617-11","Architectural & topographical installation plans/diagrams"),
     ("60617-12","617-12 (1983)","Binary logic elements"),
     ("60617-13","617-13 (1993)","Analogue elements"),
     ("60617-12-1","617-12.1","Binary logic — supplement 12.1"),
     ("60617-12-2","617-12.2","Binary logic — supplement 12.2")]

out=["# Index — IEC 60617 Symbol Knowledge Graph","",
 "Auto-generated by `tools/build_index.py` from the wiki's frontmatter. Read this",
 "first when answering a query, then drill into the section hubs and symbol nodes.",
 "See [[CLAUDE]] for conventions.","",
 f"**Status:** {len([s for s in std if not s.endswith('-1')])} parts ingested · **{nsym} symbol nodes** · "
 f"{len(glob.glob(os.path.join(WIKI,'sections','*.md')))} section hubs.","",
 "## Standards <a id=\"standards\"></a>","",
 "✅ = in collection · ⬇ = ingested into wiki · ❌ = referenced but missing from collection.","",
 "| Part | Title | Status |","|------|-------|--------|"]
INCOLL={"60617-1","60617-2","60617-3","60617-6","60617-7","60617-8","60617-9","60617-10","60617-12","60617-13","60617-12-1","60617-2-2"}
for sid,label,title in FAM:
    if sid and sid in std:
        cnt=std[sid].get("symbol_count","")
        link=f"[[{sid}]]"
        status="⬇ index + cross-correspondence" if sid=="60617-1" else f"⬇ ingested ({cnt})"
    elif sid is None:
        link=label; status="❌ missing"
    else:
        link=label; status="✅"
    out.append(f"| {link} | {title} | {status} |")
out+=["","Related standards referenced by symbols: **IEC 445, 27, 375, 364-3, 113, 416/417, 750, 1082, ISO 31, ISO 128**.",""]

# concepts
con=sorted(glob.glob(os.path.join(WIKI,"concepts","*.md")))
if con:
    out+=["## Concepts",""]
    for p in con:
        cid=os.path.splitext(os.path.basename(p))[0]
        out.append(f"- [[{cid}]]")
    out.append("")

# per-part section lists, ordered by part number
def partnum(sid):
    m=re.match(r"60617-(\d+)",sid); return int(m.group(1)) if m else 99
for sid in sorted(std, key=partnum):
    d=std[sid]
    if sid not in secs: continue
    out.append(f"## {d.get('standard',sid)} — {d.get('title_en','')}")
    out.append(f"Part page: [[{sid}]] · {d.get('symbol_count','?')} symbols.")
    out.append("")
    for secid,sd in secs[sid]:
        out.append(f"- [[{secid}]] — {sd.get('title_en','')} ({sd.get('symbol_count','')})")
    out.append("")

open(os.path.join(WIKI,"index.md"),"w").write("\n".join(out))
print(f"index.md rebuilt: {len(std)} parts, {nsym} symbols, "
      f"{len(glob.glob(os.path.join(WIKI,'sections','*.md')))} sections.")
